credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: abc # Det här ska vara ett hashat lösenord i produktion!
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com