# Google API-nyckel
GOOGLE_API_KEY = "AIzaSyDxRslVq6HCloWyxr7L-AZ5hNosbbaZRgw"

# Användaruppgifter (hashade lösenord)
# För att generera hashade lösenord, kör:
# python -c "import hashlib; print(hashlib.sha256('ditt_lösenord'.encode()).hexdigest())"

[users]
admin = "2934af9bf04ae03f5cf76fc84ddeef3254f2b1f42598183bdef3a75741a80629"  # Lösenord: "14solar"

# Lägg till fler användare här enligt samma format
# användare3 = "hashed_password"

solstrale = "ecac3997861804e6f5b8f2cdd75edf5a09831d66fd6aa75fa51fee5525933129"  # Lösenord: "25Beam8"